# Gateway TaskFlow — única entrada pública (:8080→:80).
# Prefijo /api/* se recorta al reenviar (ver "/" final en proxy_pass).

server {
    listen 80;

    # DNS interno de Docker; permite arrancar aunque falten backends (Fase 1).
    resolver 127.0.0.11 valid=10s;

    # Salud del gateway (no de los backends).
    location = /healthz {
        access_log off;
        return 200 'ok';
        add_header Content-Type text/plain;
    }

    # Auth (JWT) → .NET en puerto interno 5001.
    location /api/users/ {
        set $up_users http://users:5001;
        proxy_pass $up_users/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # CRUD tareas → Express en puerto interno 5002.
    location /api/tasks/ {
        set $up_tasks http://tasks:5002;
        proxy_pass $up_tasks/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Auditoría → Flask en puerto interno 5003.
    location /api/logs/ {
        set $up_logs http://logs:5003;
        proxy_pass $up_logs/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Frontend principal (React) en /.
    location / {
        set $up_web http://frontend-react:80;
        proxy_pass $up_web;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Frontend secundario (Angular) en /angular/.
    location /angular/ {
        set $up_ng http://frontend-angular:80;
        proxy_pass $up_ng/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
